name = "lean-learning"
version = "0.1.0"

[[lean_lib]]
name = "Untitled"

[[lean_lib]]
name = "Foundations"

[[lean_lib]]
name = "SFC"

[[lean_lib]]
name = "PL"

[[lean_lib]]
name = "Algebra"

[[lean_lib]]
name = "Misc"

[[lean_exe]]
name = "untitled"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
